# Generated by Django 5.2.8 on 2026-03-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('aunt_uncle', 'Aunt/Uncle'), ('cousin', 'Cousin'), ('other', 'Other')], max_length=20)),
                ('condition', models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('heart_disease', 'Heart Disease'), ('stroke', 'Stroke'), ('cancer', 'Cancer'), ('kidney_disease', 'Kidney Disease'), ('thyroid', 'Thyroid Disorder'), ('other', 'Other')], max_length=30)),
                ('condition_details', models.CharField(blank=True, max_length=200)),
                ('age_at_diagnosis', models.IntegerField(blank=True, null=True)),
                ('is_deceased', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Family histories',
            },
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal_type', models.CharField(choices=[('weight', 'Weight Goal'), ('exercise', 'Exercise Goal'), ('blood_sugar', 'Blood Sugar Goal'), ('bp', 'Blood Pressure Goal'), ('other', 'Other')], default='other', max_length=20)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(default=0)),
                ('unit', models.CharField(default='units', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_hypertension', models.BooleanField(default=False)),
                ('has_heart_disease', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('alcohol_consumption', models.CharField(blank=True, choices=[('none', 'None'), ('occasional', 'Occasional'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], max_length=20)),
                ('exercise_frequency', models.CharField(blank=True, choices=[('none', 'None'), ('1-2', '1-2 times per week'), ('3-4', '3-4 times per week'), ('5+', '5+ times per week')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('milestone_type', models.CharField(choices=[('prediction', 'Prediction Milestone'), ('profile', 'Profile Milestone'), ('goal', 'Goal Milestone'), ('activity', 'Activity Milestone'), ('achievement', 'Achievement')], max_length=20)),
                ('required_predictions', models.IntegerField(default=0)),
                ('required_goals', models.IntegerField(default=0)),
                ('required_days_active', models.IntegerField(default=0)),
                ('badge_icon', models.CharField(blank=True, max_length=50)),
                ('points', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_date', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
    ]
