# Generated by Django 5.2.8 on 2026-03-03 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familyhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_history_health', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthgoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_goals_health', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile_health', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermilestone',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.milestone'),
        ),
        migrations.AddField(
            model_name='usermilestone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_milestones_health', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usermilestone',
            unique_together={('user', 'milestone')},
        ),
    ]
