# Generated by Django 5.2.8 on 2026-03-03 11:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth (YYYY-MM-DD)', null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in cm (50-300 cm)', null=True, validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(300.0)])),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg (20-500 kg)', null=True, validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(500.0)])),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood type', max_length=3, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], help_text='Gender', max_length=1, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.')),
                ('email_verification_token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Token for email verification', null=True, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='Timestamp when email was verified', null=True)),
                ('password_reset_token', models.UUIDField(blank=True, help_text='Token for password reset', null=True, unique=True)),
                ('password_reset_token_created', models.DateTimeField(blank=True, help_text='Timestamp when password reset token was created', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when user was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when user was last updated')),
                ('last_password_change', models.DateTimeField(blank=True, help_text='Timestamp of last password change', null=True)),
                ('email_notifications', models.BooleanField(default=True, help_text='User wants to receive email notifications')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['is_verified'], name='users_user_is_veri_9ce429_idx'), models.Index(fields=['date_joined'], name='users_user_date_jo_064c8f_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
