"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
import logging
from datetime import timedelta
import dj_database_url

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY and DEBUG:
    # Only use fallback in development
    SECRET_KEY = 'django-insecure-oakzofm6_6wivmxwxrw37j4ff&pqoltbp_d6mlcn6^o7bz^5+f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
# Add Render domain if in production
if not DEBUG:
    RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
    if RENDER_EXTERNAL_HOSTNAME:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition
INSTALLED_APPS = [
    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'whitenoise',  # Added for static files in production
    
    # Your custom apps
    'api',
    'users',
    'predictions',
    'health',
    'user_medications',
    'user_symptoms',
    'health_resources',
    'user_dashboard',
    'ai',  # AI app for health coach features
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Added for static files
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL from environment (provided by Render) or fallback to SQLite for development
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG
        )
    }
else:
    # Fallback to SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================================
# CUSTOM SETTINGS FOR YOUR PROJECT
# ============================================================================

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# ============================================================================
# CORS SETTINGS
# ============================================================================

# CORS Settings (for React frontend on Vercel)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
]

# Add Vercel frontend URL if in production
FRONTEND_URL = os.getenv('FRONTEND_URL')
if FRONTEND_URL:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-session-id',
]

# For development only - remove in production
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True

# ============================================================================
# REST FRAMEWORK SETTINGS
# ============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
        'predictions': '60/hour',
        'burst': '10/minute',
        'ai': '50/day',  # Rate limit for AI features
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'COERCE_DECIMAL_TO_STRING': False,
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer', 'Token'),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=60),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# ============================================================================
# SESSION AND SECURITY SETTINGS
# ============================================================================

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_SECURE = not DEBUG  # True in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CSRF settings
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_SECURE = not DEBUG  # True in production
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

# Build CSRF trusted origins from allowed origins
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()
if FRONTEND_URL:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)

# ============================================================================
# EMAIL SETTINGS
# ============================================================================

if DEBUG:
    # Development email settings
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    ACCOUNT_EMAIL_VERIFICATION = 'none'
    ACCOUNT_EMAIL_REQUIRED = False
else:
    # Production email settings - configure with your email provider
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@diabetes-app.com')
    ACCOUNT_EMAIL_VERIFICATION = 'optional'
    ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[Diabetes App] '

# Site URL for email links
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# Password reset settings
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours in seconds

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# Custom filter to handle emojis in Windows console
class EmojiFilter(logging.Filter):
    """Filter to replace emojis with text equivalents for Windows console compatibility"""
    def filter(self, record):
        if hasattr(record, 'msg') and isinstance(record.msg, str):
            # Replace common emojis with text equivalents
            record.msg = record.msg.replace('✅', '[SUCCESS]')
            record.msg = record.msg.replace('❌', '[ERROR]')
            record.msg = record.msg.replace('⚠️', '[WARNING]')
            record.msg = record.msg.replace('🔍', '[INFO]')
            record.msg = record.msg.replace('🚀', '[START]')
            record.msg = record.msg.replace('📊', '[DATA]')
            record.msg = record.msg.replace('💾', '[SAVE]')
            record.msg = record.msg.replace('🔧', '[CONFIG]')
            record.msg = record.msg.replace('⚙️', '[SETUP]')
            record.msg = record.msg.replace('📝', '[LOG]')
            record.msg = record.msg.replace('🔑', '[AUTH]')
            record.msg = record.msg.replace('👤', '[USER]')
            record.msg = record.msg.replace('📧', '[EMAIL]')
            record.msg = record.msg.replace('🔒', '[SECURE]')
            record.msg = record.msg.replace('🤖', '[AI]')
        return True

# Custom JSON formatter
class JsonFormatter(logging.Formatter):
    """Custom JSON formatter for logging"""
    def format(self, record):
        import json
        from datetime import datetime
        
        log_record = {
            'timestamp': datetime.fromtimestamp(record.created).isoformat(),
            'level': record.levelname,
            'module': record.module,
            'message': record.getMessage(),
        }
        
        # Add exception info if present
        if record.exc_info:
            log_record['exception'] = self.formatException(record.exc_info)
        
        # Add custom attributes if present
        if hasattr(record, 'user_id'):
            log_record['user_id'] = record.user_id
            
        return json.dumps(log_record)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'emoji_filter': {
            '()': EmojiFilter,
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'colored': {
            'format': '\033[36m{asctime}\033[0m - \033[92m{levelname}\033[0m - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'json': {
            '()': JsonFormatter,
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'simple' if DEBUG else 'json',
            'filters': ['emoji_filter'],
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'django.log',
            'formatter': 'verbose',
            'filters': ['emoji_filter'],
            'level': 'INFO',
            'encoding': 'utf-8',
        },
        'error_file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'error.log',
            'formatter': 'verbose',
            'level': 'ERROR',
            'encoding': 'utf-8',
        },
        'predictions_file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'predictions.log',
            'formatter': 'verbose',
            'level': 'INFO',
            'encoding': 'utf-8',
        },
        'auth_file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'auth.log',
            'formatter': 'verbose',
            'level': 'INFO',
            'encoding': 'utf-8',
        },
        'ai_file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'ai.log',
            'formatter': 'verbose',
            'level': 'INFO',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'console'],
            'level': 'DEBUG' if DEBUG else 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'] if DEBUG else [],
            'level': 'DEBUG' if DEBUG else 'ERROR',
            'propagate': False,
        },
        'predictions': {
            'handlers': ['console', 'file', 'predictions_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'ai': {
            'handlers': ['console', 'file', 'ai_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# ============================================================================
# CACHE CONFIGURATION - FIXED FOR NO REDIS
# ============================================================================

# Using local memory cache - no Redis required!
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutes default
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,  # Remove 1/3 of entries when max is reached
        }
    }
}

# Session cache
SESSION_CACHE_ALIAS = 'default'

# Cache timeouts for AI features
AI_CACHE_TIMEOUT = 300  # 5 minutes
MEAL_PLAN_CACHE_TIMEOUT = 3600  # 1 hour
SYMPTOM_ANALYSIS_CACHE_TIMEOUT = 1800  # 30 minutes

# ============================================================================
# OPENROUTER AI SETTINGS
# ============================================================================

# OpenRouter API settings
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY', '')
OPENROUTER_BASE_URL = os.getenv('OPENROUTER_BASE_URL', 'https://openrouter.ai/api/v1')
OPENROUTER_DEFAULT_MODEL = os.getenv('OPENROUTER_DEFAULT_MODEL', 'google/gemma-3-12b-it:free')

# Your site info for OpenRouter (helps them track usage)
OPENROUTER_SITE_URL = os.getenv('OPENROUTER_SITE_URL', SITE_URL)
OPENROUTER_SITE_NAME = os.getenv('OPENROUTER_SITE_NAME', 'Diabetes Health Coach')

# Available models for different features
AI_MODELS = {
    'chat': os.getenv('AI_CHAT_MODEL', 'google/gemma-3-12b-it:free'),
    'meal_plan': os.getenv('AI_MEAL_PLAN_MODEL', 'meta-llama/llama-3-8b-instruct:free'),
    'symptom_analysis': os.getenv('AI_SYMPTOM_MODEL', 'microsoft/phi-3-mini-128k-instruct:free'),
    'health_tips': os.getenv('AI_TIPS_MODEL', 'deepseek/deepseek-chat:free'),
}

# Model parameters
AI_TEMPERATURE = {
    'chat': 0.7,
    'meal_plan': 0.8,
    'symptom_analysis': 0.5,  # More conservative for medical advice
    'health_tips': 0.6,
}

AI_MAX_TOKENS = {
    'chat': 500,
    'meal_plan': 1500,
    'symptom_analysis': 600,
    'health_tips': 300,
}

# Rate limiting for AI features
AI_RATE_LIMITS = {
    'chat': '50/day',
    'meal_plan': '10/day',
    'symptom_analysis': '20/day',
}

# ============================================================================
# SECURITY SETTINGS FOR PRODUCTION
# ============================================================================

if not DEBUG:
    # Security middleware settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Remove development-only CORS settings
    CORS_ALLOW_ALL_ORIGINS = False
    
    # Production logging level
    LOGGING['root']['level'] = 'WARNING'
    LOGGING['loggers']['django']['level'] = 'WARNING'
    LOGGING['loggers']['ai']['level'] = 'INFO'  # Keep AI logging for monitoring

# ============================================================================
# CUSTOM APP SPECIFIC SETTINGS
# ============================================================================

# Prediction settings
PREDICTION_THRESHOLD_HIGH = float(os.getenv('PREDICTION_THRESHOLD_HIGH', 0.7))
PREDICTION_THRESHOLD_LOW = float(os.getenv('PREDICTION_THRESHOLD_LOW', 0.3))
MAX_PUBLIC_PREDICTIONS_PER_SESSION = int(os.getenv('MAX_PUBLIC_PREDICTIONS_PER_SESSION', 3))

# Health settings
BMI_MIN = 10
BMI_MAX = 60
GLUCOSE_MIN = 70
GLUCOSE_MAX = 300
AGE_MIN = 18
AGE_MAX = 120

# Feature importance thresholds
MIN_FEATURE_IMPORTANCE = float(os.getenv('MIN_FEATURE_IMPORTANCE', 0.05))

# API rate limiting
RATE_LIMIT_PUBLIC_PREDICTIONS = '3/hour'
RATE_LIMIT_AUTH_PREDICTIONS = '100/hour'

# ML Model paths
ML_MODELS_DIR = BASE_DIR / 'ml_models'
MODEL_PATH = ML_MODELS_DIR / 'model.pkl'
SCALER_PATH = ML_MODELS_DIR / 'scaler.pkl'
FEATURE_NAMES_PATH = ML_MODELS_DIR / 'feature_names.json'